input {
  beats {
    port => 5044
  }
  udp {
    port  => 5140
    codec => plain
    type  => "syslog"
  }
}

filter {
  if [type] == "syslog" {
    grok {
      match => {
        "message" => "%{SYSLOGTIMESTAMP:ts} %{SYSLOGHOST:host_src} %{DATA:prog}(?:\[%{POSINT:pid}\])?: %{GREEDYDATA:msg}"
      }
    }
  }
}

output {
  elasticsearch {
    hosts    => ["http://elasticsearch:9200"]
    user     => "elastic"
    # Mot de passe injecté via variable d'environnement ELASTIC_PASSWORD dans docker-compose.yml
    password => "${ELASTIC_PASSWORD}"
    index    => "logs-%{+YYYY.MM.dd}"
  }
}
