# Regles de detection Kibana SIEM

| Regle | Type | Event ID | Severite | Risk | MITRE |
|---|---|---|---|---|---|
| Brute Force connexion | Threshold >=5 | 4625 | High | 75 | T1110 |
| PowerShell encode | Query | 4104 | High |cd "C:\Users\t.escalona\OneDrive - Association Cesi Viacesi mail\Personnel\GitHub\Mini-SOC"

# Créer les dossiers manquants
New-Item -ItemType Directory -Path "thehive" -Force
New-Item -ItemType Directory -Path "opencti" -Force
New-Item -ItemType Directory -Path "detection-rules" -Force
New-Item -ItemType Directory -Path "docs" -Force

# Dockerfile-cortex
@"
FROM thehiveproject/cortex:3.1.8
USER root
RUN rm -f /etc/apt/sources.list.d/corretto.list && \
    apt-get update -qq && \
    apt-get install -y python3-pip && \
    pip3 install cortexutils requests Pillow pyOpenSSL python-dateutil && \
    apt-get clean
